blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_index_slash:
    path:     /blog/
    defaults: { _controller: BlogBundle:Default:list,  page: 1}

blog_list:
    path:     /blog/{page}
    defaults: { _controller: BlogBundle:Default:list, page: 1 }
    requirements:
        page: '\d+'

blog_show:
    path:     /blog/{slug}
    defaults: { _controller: BlogBundle:Default:show }

blog_stream:
    path:     /blogstream/{slug}
    defaults: { _controller: BlogBundle:Default:stream }
